language: elixir
elixir: '1.5.2'
otp_release: '19.0'

install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

env:
  - MIX_ENV=test

script:
  - "mix do test && mix compile && mix coveralls.travis"
